apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: vaishven/timeslide:latest  # Replace with your Docker Hub image path
        ports:
        - containerPort: 80  # Replace with the port your app uses

